### ISSUE TITLE
Nuget package can not work corect

### ISSUE THREAD

**Issue by heyixiaoran** [zachatrocity/netoaster#12]
I install this package from Nuget. It can not work corect.  'Toaster ' does  not contain a definition for 'ShowSuccess' , 'ShowWarning' and 'ShowError' .But if I reference from netoaster project .It is corect. 
![k8js69d on l i2s0d6tg](https://cloud.githubusercontent.com/assets/5743795/21590229/e2e89010-d134-11e6-94c2-2cc313213d0c.png)

**Comment by zachatrocity** [comment]
I'll spin up a windows VM this weekend and take a look.

**Comment by tangible-idea** [comment]
I'm having same pbm.. but it works with cloned project.

**Comment by leopucci-zz** [comment]
Nuget package is wrong, the dependencies are not set, PresentationCore, PresentationFramework, WindowsBase. You have to set on your nuget package. 
Also there is no ShowSucces classes like @heyixiaoran  said.

**Comment by zachatrocity** [comment]
Yeah I see that. Pretty swamped lately. I would love to accept a PR with the nuget package config

**Comment by leopucci-zz** [comment]
Haha
Who wouldn't.. lol

Maybe next weekend i give a shot

Regards

Pucci



Em 06/03/2017 14:48, "Zach Russell" <notifications@github.com> escreveu:

Yeah I see that. Pretty swamped lately. I would love to accept a PR with
the nuget package config

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/zachatrocity/netoaster/issues/12#issuecomment-284474837>,
or mute the thread
